### ISSUE TITLE
Latest Fulcio panics.

### ISSUE THREAD

**Issue by vaikas** [sigstore/scaffolding#298]
**Description**

Observed now couple of times that with k8s 1.24 and latest Fulcio, it panics. 

```
2022-08-16T08:25:21.139782613Z stderr F fatal error: unexpected signal during runtime execution
2022-08-16T08:25:21.141867116Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x47 pc=0x7f2805131360]
2022-08-16T08:25:21.141874416Z stderr F 
2022-08-16T08:25:21.141878016Z stderr F runtime stack:
2022-08-16T08:25:21.141940516Z stderr F runtime.throw({0x153b32d?, 0x7f2805169b00?})
2022-08-16T08:25:21.142050316Z stderr F 	runtime/panic.go:992 +0x71
2022-08-16T08:25:21.142066916Z stderr F runtime.sigpanic()
2022-08-16T08:25:21.142071016Z stderr F 	runtime/signal_unix.go:802 +0x3a9
2022-08-16T08:25:21.142073816Z stderr F 
2022-08-16T08:25:21.142076616Z stderr F goroutine 12 [syscall]:
2022-08-16T08:25:21.142079516Z stderr F runtime.cgocall(0x112f960, 0xc000063598)
2022-08-16T08:25:21.142125416Z stderr F 	runtime/cgocall.go:157 +0x5c fp=0xc000063570 sp=0xc000063538 pc=0x40575c
2022-08-16T08:25:21.142129316Z stderr F net._C2func_getaddrinfo(0xc000045bf0, 0x0, 0xc00078e5a0, 0xc000010098)
2022-08-16T08:25:21.142132216Z stderr F 	_cgo_gotypes.go:94 +0x56 fp=0xc000063598 sp=0xc000063570 pc=0x5d21d6
2022-08-16T08:25:21.142135016Z stderr F net.cgoLookupIPCNAME.func1({0xc000045bf0, 0x0?, 0x0?}, 0xc000045b90?, 0x5d881b?)
2022-08-16T08:25:21.142137716Z stderr F 	net/cgo_unix.go:160 +0x9f fp=0xc0000635f0 sp=0xc000063598 pc=0x5d3eff
2022-08-16T08:25:21.142140616Z stderr F net.cgoLookupIPCNAME({0x14fc6a5, 0x3}, {0xc000045b90, 0x24})
2022-08-16T08:25:21.142358117Z stderr F 	net/cgo_unix.go:160 +0x16d fp=0xc000063738 sp=0xc0000635f0 pc=0x5d376d
2022-08-16T08:25:21.142633817Z stderr F net.cgoIPLookup(0x218f630?, {0x14fc6a5?, 0xc000045bc0?}, {0xc000045b90?, 0xc0002ea370?})
2022-08-16T08:25:21.142792817Z stderr F 	net/cgo_unix.go:217 +0x3b fp=0xc0000637a8 sp=0xc000063738 pc=0x5d3fbb
2022-08-16T08:25:21.142819017Z stderr F net.cgoLookupIP.func1()
2022-08-16T08:25:21.142895117Z stderr F 	net/cgo_unix.go:227 +0x36 fp=0xc0000637e0 sp=0xc0000637a8 pc=0x5d43f6
2022-08-16T08:25:21.142899417Z stderr F runtime.goexit()
2022-08-16T08:25:21.142902317Z stderr F 	runtime/asm_amd64.s:1571 +0x1 fp=0xc0000637e8 sp=0xc0000637e0 pc=0x469101
2022-08-16T08:25:21.142905417Z stderr F created by net.cgoLookupIP
2022-08-16T08:25:21.142908117Z stderr F 	net/cgo_unix.go:227 +0x12a
2022-08-16T08:25:21.142910717Z stderr F 
2022-08-16T08:25:21.142913817Z stderr F goroutine 1 [select]:
2022-08-16T08:25:21.143025618Z stderr F net/http.(*Transport).getConn(0xc00075f7c0, 0xc0002a9040, {{}, 0x0, {0xc000775f90, 0x5}, {0xc000045b90, 0x28}, 0x0})
2022-08-16T08:25:21.143029518Z stderr F 	net/http/transport.go:1375 +0x5c6
2022-08-16T08:25:21.143032718Z stderr F net/http.(*Transport).roundTrip(0xc00075f7c0, 0xc0000e3600)
2022-08-16T08:25:21.143035618Z stderr F 	net/http/transport.go:581 +0x76f
2022-08-16T08:25:21.143038418Z stderr F net/http.(*Transport).RoundTrip(0x0?, 0x1854d20?)
2022-08-16T08:25:21.143041218Z stderr F 	net/http/roundtrip.go:17 +0x19
2022-08-16T08:25:21.143044218Z stderr F net/http.send(0xc0000e3600, {0x1854d20, 0xc00075f7c0}, {0x14d1540?, 0x1?, 0x0?})
2022-08-16T08:25:21.143047018Z stderr F 	net/http/client.go:252 +0x5d8
2022-08-16T08:25:21.143109618Z stderr F net/http.(*Client).send(0x2190400, 0xc0000e3600, {0x0?, 0xc0006dd318?, 0x0?})
2022-08-16T08:25:21.143113818Z stderr F 	net/http/client.go:176 +0x9b
2022-08-16T08:25:21.143117018Z stderr F net/http.(*Client).do(0x2190400, 0xc0000e3600)
2022-08-16T08:25:21.143119718Z stderr F 	net/http/client.go:725 +0x8f5
2022-08-16T08:25:21.143122518Z stderr F net/http.(*Client).Do(...)
2022-08-16T08:25:21.143125318Z stderr F 	net/http/client.go:593
2022-08-16T08:25:21.143128418Z stderr F github.com/coreos/go-oidc/v3/oidc.doRequest({0x185f308, 0xc000280600}, 0xc0000e2600)
2022-08-16T08:25:21.143131418Z stderr F 	github.com/coreos/go-oidc/v3@v3.2.0/oidc/oidc.go:96 +0x21e
2022-08-16T08:25:21.143134218Z stderr F github.com/coreos/go-oidc/v3/oidc.NewProvider({0x185f308, 0xc000280600}, {0xc0001be390, 0x2c})
2022-08-16T08:25:21.143137018Z stderr F 	github.com/coreos/go-oidc/v3@v3.2.0/oidc/oidc.go:189 +0x136
2022-08-16T08:25:21.143139818Z stderr F github.com/sigstore/fulcio/pkg/config.(*FulcioConfig).prepare(0xc0002ad620)
2022-08-16T08:25:21.143714119Z stderr F 	github.com/sigstore/fulcio/pkg/config/config.go:194 +0x16f
2022-08-16T08:25:21.143893519Z stderr F github.com/sigstore/fulcio/pkg/config.Read({0xc000260000?, 0x0?, 0x184f040?})
2022-08-16T08:25:21.143904619Z stderr F 	github.com/sigstore/fulcio/pkg/config/config.go:419 +0x2f5
2022-08-16T08:25:21.143907619Z stderr F github.com/sigstore/fulcio/pkg/config.Load({0x15204e1, 0x1e})
2022-08-16T08:25:21.143974819Z stderr F 	github.com/sigstore/fulcio/pkg/config/config.go:378 +0x1ae
2022-08-16T08:25:21.143979319Z stderr F github.com/sigstore/fulcio/cmd/app.runServeCmd(0xc000239b80, {0x14fce1f?, 0x9?, 0x9?})
2022-08-16T08:25:21.143982219Z stderr F 	github.com/sigstore/fulcio/cmd/app/serve.go:184 +0x91d
2022-08-16T08:25:21.14470852Z stderr F github.com/spf13/cobra.(*Command).execute(0xc000239b80, {0xc0003a2a20, 0x9, 0x9})
2022-08-16T08:25:21.14471342Z stderr F 	github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
2022-08-16T08:25:21.14471632Z stderr F github.com/spf13/cobra.(*Command).ExecuteC(0x2107800)
2022-08-16T08:25:21.14471952Z stderr F 	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
2022-08-16T08:25:21.14472242Z stderr F github.com/spf13/cobra.(*Command).Execute(...)
2022-08-16T08:25:21.14472532Z stderr F 	github.com/spf13/cobra@v1.5.0/command.go:918
2022-08-16T08:25:21.14472812Z stderr F github.com/spf13/cobra.(*Command).ExecuteContext(...)
2022-08-16T08:25:21.14473092Z stderr F 	github.com/spf13/cobra@v1.5.0/command.go:911
2022-08-16T08:25:21.14473382Z stderr F github.com/sigstore/fulcio/cmd/app.Execute({0x185f2d0?, 0xc000048040?})
2022-08-16T08:25:21.14473692Z stderr F 	github.com/sigstore/fulcio/cmd/app/root.go:37 +0x57
2022-08-16T08:25:21.14473972Z stderr F main.main()
2022-08-16T08:25:21.14474252Z stderr F 	github.com/sigstore/fulcio/main.go:25 +0x27
2022-08-16T08:25:21.14474522Z stderr F 
2022-08-16T08:25:21.14474822Z stderr F goroutine 6 [chan receive]:
2022-08-16T08:25:21.14475102Z stderr F github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
2022-08-16T08:25:21.14475382Z stderr F 	github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
2022-08-16T08:25:21.14475662Z stderr F created by github.com/golang/glog.init.0
2022-08-16T08:25:21.14476372Z stderr F 	github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf
2022-08-16T08:25:21.14476652Z stderr F 
2022-08-16T08:25:21.14476942Z stderr F goroutine 29 [select]:
2022-08-16T08:25:21.14477222Z stderr F go.opencensus.io/stats/view.(*worker).start(0xc000302200)
2022-08-16T08:25:21.14477512Z stderr F 	go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
2022-08-16T08:25:21.14477802Z stderr F created by go.opencensus.io/stats/view.init.0
2022-08-16T08:25:21.14478072Z stderr F 	go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d
2022-08-16T08:25:21.14478342Z stderr F 
2022-08-16T08:25:21.14478612Z stderr F goroutine 10 [select]:
2022-08-16T08:25:21.14478922Z stderr F net.(*Resolver).lookupIPAddr(0x218f620, {0x185f308?, 0xc000280600}, {0x14fc6a5, 0x3}, {0xc000045b90, 0x24})
2022-08-16T08:25:21.14479202Z stderr F 	net/lookup.go:325 +0x51b
2022-08-16T08:25:21.14479512Z stderr F net.(*Resolver).internetAddrList(0x185f308?, {0x185f308?, 0xc000280600?}, {0x14fc6a5, 0x3}, {0xc000045b90?, 0x28?})
2022-08-16T08:25:21.14479792Z stderr F 	net/ipsock.go:288 +0x67a
2022-08-16T08:25:21.14480092Z stderr F net.(*Resolver).resolveAddrList(0x21c76e0?, {0x185f308, 0xc000280600}, {0x14fcd43, 0x4}, {0x14fc6a5?, 0x0?}, {0xc000045b90, 0x28}, {0x0, ...})
2022-08-16T08:25:21.14480372Z stderr F 	net/dial.go:221 +0x41b
2022-08-16T08:25:21.14480692Z stderr F net.(*Dialer).DialContext(0xc00008c2a0, {0x185f308, 0xc000280600}, {0x14fc6a5, 0x3}, {0xc000045b90, 0x28})
2022-08-16T08:25:21.14480972Z stderr F 	net/dial.go:406 +0x448
2022-08-16T08:25:21.14481262Z stderr F net/http.(*Transport).dial(0x0?, {0x185f308?, 0xc000280600?}, {0x14fc6a5?, 0x0?}, {0xc000045b90?, 0x0?})
2022-08-16T08:25:21.14481542Z stderr F 	net/http/transport.go:1169 +0xda
2022-08-16T08:25:21.14481842Z stderr F net/http.(*Transport).dialConn(0xc00075f7c0, {0x185f308, 0xc000280600}, {{}, 0x0, {0xc000775f90, 0x5}, {0xc000045b90, 0x28}, 0x0})
2022-08-16T08:25:21.14482612Z stderr F 	net/http/transport.go:1607 +0x83f
2022-08-16T08:25:21.14482892Z stderr F net/http.(*Transport).dialConnFor(0x0?, 0xc0002ea370)
2022-08-16T08:25:21.14483172Z stderr F 	net/http/transport.go:1449 +0xb0
2022-08-16T08:25:21.14483452Z stderr F created by net/http.(*Transport).queueForDial
2022-08-16T08:25:21.14483732Z stderr F 	net/http/transport.go:1418 +0x3d2
2022-08-16T08:25:21.14484002Z stderr F 
2022-08-16T08:25:21.14484272Z stderr F goroutine 11 [select]:
2022-08-16T08:25:21.14484552Z stderr F net.cgoLookupIP({0x185f298, 0xc0002a90c0}, {0x14fc6a5, 0x3}, {0xc000045b90, 0x24})
2022-08-16T08:25:21.14484852Z stderr F 	net/cgo_unix.go:228 +0x1aa
2022-08-16T08:25:21.14485142Z stderr F net.(*Resolver).lookupIP(0x218f620, {0x185f298, 0xc0002a90c0}, {0x14fc6a5, 0x3}, {0xc000045b90, 0x24})
2022-08-16T08:25:21.14485422Z stderr F 	net/lookup_unix.go:96 +0x128
2022-08-16T08:25:21.14485702Z stderr F net.glob..func1({0x185f298?, 0xc0002a90c0?}, 0x0?, {0x14fc6a5?, 0x0?}, {0xc000045b90?, 0x82b450?})
2022-08-16T08:25:21.14485982Z stderr F 	net/hook.go:23 +0x3d
2022-08-16T08:25:21.14486282Z stderr F net.(*Resolver).lookupIPAddr.func1()
2022-08-16T08:25:21.14486552Z stderr F 	net/lookup.go:319 +0x9f
2022-08-16T08:25:21.14486842Z stderr F internal/singleflight.(*Group).doCall(0x218f630, 0xc0000974f0, {0xc000045bc0, 0x28}, 0xc0002ea370?)
2022-08-16T08:25:21.14487142Z stderr F 	internal/singleflight/singleflight.go:95 +0x3b
2022-08-16T08:25:21.14487412Z stderr F created by internal/singleflight.(*Group).DoChan
2022-08-16T08:25:21.14487682Z stderr F 	internal/singleflight/singleflight.go:88 +0x2ec
```

Then it restarts seemingly fine after some more time:
```
2022-08-16T08:25:48.328892481Z stdout F 2022-08-16T08:25:48.328Z	[34mINFO[0m	app/grpc.go:103	listening on grpc at :::8081
2022-08-16T08:25:48.328990281Z stdout F 2022-08-16T08:25:48.328Z	[34mINFO[0m	app/grpc.go:121	listening on grpc at @fulcio-legacy-grpc-socket
2022-08-16T08:25:48.329770382Z stdout F 2022-08-16T08:25:48.329Z	[34mINFO[0m	app/http.go:89	listening on http at 0.0.0.0:5555

```

**Version**
Scaffolding: Head
Fulcio 0.5.2

**Comment by vaikas** [comment]
One example here:
https://github.com/sigstore/scaffolding/runs/7853574221?check_suite_focus=true

However, it does come up, just takes a bit of time. Nothing out of the stack trace jumps at me.

```
--- fulcio-system pods ---
NAME                                       READY   STATUS      RESTARTS      AGE
createcerts-kwl6r                          0/1     Completed   0             59s
fulcio-00001-deployment-697d55ffcf-gc7vc   2/2     Running     3 (33s ago)   58s

```

**Comment by vaikas** [comment]
I have not seen a single instance of fulcio panicing when using the netdns=go, so I'm closing this for now. We can reopen if necessary.
There's some discussion about building releases without cgo support, so if that happens, we could switch to using that.
